name: Test

on:
  pull_request:
  push:
    branches:
      - main
      - release

jobs:
  test:
    name: Test (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '7.2' ]
        phpunit: [ '7.5' ]

    env:
      PHP_EXTENSIONS: 'json mbstring'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Installing dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}
          php_extensions: ${{ env.PHP_EXTENSIONS }}

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --error-format=github

      - name: Running unit tests
        uses: php-actions/phpunit@v3
        with:
          version: ${{ matrix.phpunit }}
          php_version: ${{ matrix.php }}
          php_extensions: ${{ env.PHP_EXTENSIONS }}
          args: "-d date.timezone=Europe/Berlin"
          memory_limit: 300M
          configuration: phpunit.xml
          testsuite: "Apivalk Unit Tests"
